spring.application.name=backend

# ==== MySQL ====
# IMPORTANT : host = nom du service Docker Compose (mysql-db)
# PAS localhost ! Car le backend tourne dans un AUTRE conteneur que MySQL
spring.datasource.url=jdbc:mysql://mysql-db:3306/test_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==== JPA / Hibernate ====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==== Serveur ====
server.port=8080
